---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : dinky
production_url : http://montdore.ruhoh.com

posts:
  permalink: /:categories/:title/
  summary_lines: 3
  latest: 5

pages:
  permalink: 'pretty'